config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'session/index'
  resources :session, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'signup#index'

  # get "signup", to: "signup#index"
  resources :signup, only: [:index, :destroy]
  resources :signup do
    collection do
      get 'step1'
      post 'step2'
      post 'step3'
      get 'complete_signup'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user, optional: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def index
  end
  
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def index
    @users = User.all
    @profiles = Profile.all
  end

  def step1
    # step1.html.haml内のform_forで利用するためのインスタンス変数の作成
    @user = User.new
    @profile = Profile.new

    # この時点では@user,@profileはnewアクションで生成されただけの
    # 空のインスタンスなのでbinding.pryの結果は全て: nill
  end

  
  def step2
    # sessionの各キーへ代入
    session[:email] = user_params[:email]
    session[:name] = user_params[:name]
    session[:family] = user_profile_params[:family]

    # step2.html.haml内のform_forで利用するためのインスタンス変数の作成
    @profile = Profile.new
  end

  def step3
    # sessionの各キーへ代入
    session[:number] = profile_params[:number]

    # step3.html.haml内のform_forで利用するためのインスタンス変数の作成
    @profile = Profile.new
  end


  def create
    # sessionの各キーへ代入
    session[:city] = profile_params[:city]

    # sessionから保存すべきインスタンス変数へ再代入していく。
    @user = User.new(
      name: session[:name],
      email: session[:email],
      password: 111111,
      password_confirmation: 111111
    )
    @profile = Profile.new(
      family: session[:family],
      number: session[:number],
      city: session[:city]
    )
    # もし再代入されたものがバリデーションにひっかからなければ保存。
    if @user.valid? && @profile.valid?
      @user.save
      @profile.save
      redirect_to action: 'index'
    else
      # 保存できなかった(バリデーションにひかかった)場合は1ページ目からやり直し。
      redirect_to action: 'step1'
    end
  end

  def destroy
    profile = Profile.find(params[:id])
    user = User.find(params[:id])
    profile.destroy
    user.destroy
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email
    ).merge(password: 111111,password_confirmation: 111111)
  end

  def profile_params
    params.require(:profile).permit(
      :number,
      :city
    )
  end

  def user_profile_params
    params.require(:user).require(:profile).permit(
      :family
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Session
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/signup/complete_signup.html.haml
= link_to "/" do
  戻る

app/views/signup/destroy.html.haml
.action-btn
  = link_to "/" do
    削除完了！

app/views/signup/index.html.haml
.action-btn
  = link_to step1_signup_index_path do
    登録する！
.user-puts.btn
  %h1 userモデル
  - @users.each do |user|
    .boxes
      .name.box
        %p name
        = user.name
      .email.box
        %p email
        = user.email
.profile-puts.btn
  %h1 profileモデル
  - @profiles.each do |profile|
    .boxes
      .family.box
        %p family
        = profile.family
      .number.box
        %p number
        = profile.number
      .city.box
        %p city
        = profile.city
    .action-btn
      = link_to '削除', "/signup/#{profile.id}", method: :delete

app/views/signup/step1.html.haml
.forms
  = form_for @user, url: step2_signup_index_path do |f|
    .form-box
      = f.label :email, "メールアドレス(email)"
      = f.text_field :email, class: "form"
    .form-box
      = f.label :name, "名前(name)"
      = f.text_field :name, class: "form"

    = f.fields_for @profile do |p|
      .form-box
        = p.label :family, "家族(family)"
        = p.text_field :family, class: "form"
    .form-box
      = f.submit '次のページへ', class: "submit"

app/views/signup/step2.html.haml
.forms
  = form_for @profile, url: step3_signup_index_path do |f|
    
    .form-box
      = f.label :number, "携帯電話の番号"
      = f.text_field :number, class: "form"
    
    .form-box
      = f.submit '次のページへ', class: "submit"

app/views/signup/step3.html.haml
.forms
  = form_for @profile, url: signup_index_path, method: :post do |f|
    
    .form-box
      = f.label :city, "市区町村"
      = f.text_field :city, class: "form"
    
    .form-box
      = f.submit '登録を完了する', class: "submit"